### PR TITLE
Preliminary release notes for 0.8

### PR DESCRIPTION
**Pull request by kimgr**
I think this covers most of the major changes.

I tweaked the wording ever so slightly to be less personal, hope you're OK with that.

Idle thought: the mixing of real names and GitHub usernames looks a little ugly. Maybe we should list them separately, or always use the GH names?

### CODE REVIEW

**Comment by vsapsai** [comment]
Thanks for summarizing the changes. I checked and it's not straightforward.

I am totally fine with less personal wording. The first time "I" seemed appropriate and became slightly awkward afterwards.

As for me, I prefer real names. If GitHub user has real name in profile, I would use that one. And if a contributor has objections, we'll use the preferred name.

**Comment by vsapsai** [comment]
We need to update the release notes to reflect the cherry-picked changes:
* mention Kristoffer Henriksson as he contributed [IWYU pragma enhancement](https://github.com/include-what-you-use/include-what-you-use/commit/a2d8e282502cd6018b33f307519ba971b7cc11c2)
* mention the following high-level changes:
  * better function pointers support
  * documentation improvements
  * extend `IWYU pragma: keep` to work with forward declarations
  * fix handling Windows paths in `fix_includes.py`
  * better libc++ container support

There are a few commits not reflected in the list, feel free to add them if necessary.

**Comment by kimgr** [comment]
There, I think this covers most of it.

I changed the Clang version to 4.0.0, since the Windows binaries were built against that, and you had problems with 4.0.1 on the Mac.

Still no hard release date, maybe you can update that just before you push it to the website?

**Comment by vsapsai** [comment]
Everything looks good to me. I've added trailing dots for list items not ending with code and updated  list of all downloads. Preview is available at https://test.include-what-you-use.org/

**Comment by kimgr** [comment]
Looks good to me! Ship it!

**Pull request merged**
